package com.example.datexheck;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;

import com.example.datexheck.database.DatabaseHelper;
import com.example.datexheck.entities.Product;
import com.example.datexheck.recyclerview.OnProductListener;
import com.example.datexheck.recyclerview.ProductViewAdapter;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import java.util.List;

import static com.example.datexheck.entities.Constants.ADD_PRODUCT_ACTIVITY_CODE;

public class ListActivity extends AppCompatActivity {

    List<Product> products;
    ProductViewAdapter adapter;
    DatabaseHelper database;
    View rootView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list);

        FloatingActionButton addButton = findViewById(R.id.addActionButton);
        addButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                addNewItem();
            }
        });

        rootView = findViewById(R.id.content).getRootView();

        RecyclerView productRecyclerView = findViewById(R.id.productRecyclerView);

        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);


        GridLayoutManager gridLayoutManager = new GridLayoutManager(this, 1, GridLayoutManager.VERTICAL, false);

        productRecyclerView.setLayoutManager(gridLayoutManager);


        //Load Data from the database
        database = DatabaseHelper.getInstance(this);
        products = database.getProducts();
        //create adapter passing the data, and the context
        adapter = new ProductViewAdapter(products, this, (OnProductListener) this);
        //attach the adapter to the Recyclerview
        productRecyclerView.setAdapter(adapter);
    }


    //add button behaviour

    private void addNewItem() {
        Intent goToCreateProduct = new Intent(this, AddProductActivity.class);
        //open an activity waiting for a result
        startActivityForResult(goToCreateProduct, ADD_PRODUCT_ACTIVITY_CODE);

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == ADD_PRODUCT_ACTIVITY_CODE) {
            if (resultCode == RESULT_OK) {
                addProduct(data);
            }
        } else {
            finish();

        }


    }

    private void addProduct(Intent data) {

        String message;
        Product product = (Product) data.getSerializableExtra(Product.PRODUCT_KEY);
        //insert the product into the DB

        Long result = database.insert(product.getName(), product.getExpDate(), product.getBarcode());
        //result holds the autogenerated id in the table
        if (result != -1) {
            product = database.getProduct(result);
            //try Always to use the adapter to modify the elements of your RecyclerView
            adapter.addItem(product);
            message = getString(R.string.create_product_succeeded_message);
        } else {
            message = getString(R.string.create_product_failed_message);
        }
        Snackbar.make(rootView, message, Snackbar.LENGTH_SHORT).show();
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }


}
